BOARD_BOOT_HEADER_VERSION := 3
AB_OTA_PARTITIONS += vendor_boot

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a76

# TWRP
TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1600
